language: ruby
rvm:
 - 2.2
 - jruby
 - rbx-2
sudo: required 
deploy:
   edge: true
   provider: cloudfoundry
   username: hulk_hogan@example.com
   password: supersecretpassword
   api: https://api.run.pivotal.io
   organization: myawesomeorganization
   space: staging

