multipart.maxFileSize: 640KB
multipart.maxRequestSize: 640KB
cloud:
  aws:
    region: us-east-1
    bucket: joshsbucket
security:
  oauth2:
    client:
      clientId: ad11af39b5a9f97f6072
      clientSecret: bd673452cb812a7de40765bf7adb7238dda5d728
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      tokenName: access_token
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
